### ISSUE TITLE
Test dvshimmer water effect and crop

### ISSUE THREAD

**Issue by michela** [georgekhut/moodLabVisuals#7]
https://vimeo.com/230442236/5e48817d94

Howse this?

**Comment by michela** [comment]
https://vimeo.com/230600802/dbc9654909

Ready for another session - see latest commit

**Comment by georgekhut** [comment]
Hi Michela
The crop and feather is excellent. Jitter is working well – but will need some refinement to better approximate the feeling that the colloids/particles are floating/drifting. 
Have a look at the screencast I uploaded - re the perlin shimmer / glimmer effects
https://vimeo.com/230686854/5a29306a61

**Comment by michela** [comment]
Can you check perms, broken link for me

**Comment by michela** [comment]
Copied the Monday defaults for water webcam and looks ok again in latest push. See what you think

**Comment by georgekhut** [comment]
Re cropping, positioning, sizing and feathering of webcam input:
Can the location and dimensions of the feathering effect be set independently of the edges of the webcam input? The intention is that feathering is applied to a mask/crop - so that the camera image appears as a soft shape in the center of the screen. This can be achieved with the current code – but only if the webcam image is evenly centred using the "/gfx/dvshimmer/Pos" messages.
In practice - the image of the participant in the webcam needs to me moved upwards toward the top . of the screen. When this happens – the feather effects is lost at the top of the image

**Comment by michela** [comment]
Show you like v232. I've pushed update that does position, rot, scaling and cropping prior to the shader (using the legacy feather shader which isn't symetrical).

Also, pushed major improvement to tanks:
https://github.com/georgekhut/moodLabVisuals/wiki

**Comment by michela** [comment]
> make sure used for matte as well

What do you mean by matte?
